apiVersion: v1
kind: Secret
metadata:
  name: s3-creds
  namespace: kserve-deployement
  annotations:
     serving.kserve.io/s3-endpoint: 10.107.130.224:9000 # replace with your s3 endpoint e.g minio-service.kubeflow:9000
     serving.kserve.io/s3-usehttps: "0" # by default 1, if testing with minio you can set to 0
     serving.kserve.io/s3-region: "us-east-2"
     serving.kserve.io/s3-useanoncredential: "false" # omitting this is the same as false, if true will ignore provided credential and use anonymous credentials
type: Opaque
stringData: # use `stringData` for raw credential string or `data` for base64 encoded string
  AWS_S3_ENDPOINT_URL: 10.107.130.224:9000
  AWS_ACCESS_KEY_ID: minio
  AWS_SECRET_ACCESS_KEY: Do&BfNOtNcWqGtWV5i
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: stminio
  namespace: kserve-deployement
secrets:
- name: s3-creds
